global using MediatR;
global using FluentValidation;
global using Microsoft.Extensions.Logging;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Http;
global using CommentApp.Application.CQRS;
global using CommentApp.Application.Dtos;
global using CommentApp.Application.Data;
global using CommentApp.Application.Pagination;
global using CommentApp.Application.Exceptions;
global using CommentApp.Application.Extensions;
global using CommentApp.Application.Services.FileService;
global using CommentApp.Application.Services.HtmlSanitizerService;
global using CommentApp.Domain.Models;
global using CommentApp.Domain.Events;
global using CommentApp.Domain.ValueObjects;
global using CommentApp.Shared.Exceptions;
global using File = CommentApp.Domain.Models.File;
